version: '3'
services:
  postgres-service:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres_password
    ports:
      - '5432:5432'

  app-service:
    stdin_open: true
    build:
      context: ./app-service
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./app-service:/app
    restart: on-failure

  next-service:
    build:
      context: ./next-service
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - /app/node_modules
      - ./next-service:/app
    restart: on-failure

  api-service:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /app/node_modules
      - ./api-service:/app
    depends_on:
      - postgres-service
    ports:
      - '5000:5000'
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
